refactor(tmux-sessionizer): add loop for dependency check

diff --git a/custom/local-bin/tmux-sessionizer b/custom/local-bin/tmux-sessionizer
--- a/custom/local-bin/tmux-sessionizer
+++ b/custom/local-bin/tmux-sessionizer
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
-command -v fd >/dev/null 2>&1 || { echo 'fd is required but not installed' >&2; exit 1; }
-command -v fzf >/dev/null 2>&1 || { echo 'fd is required but not installed' >&2; exit 1; }
+for cmd in fd fzf; do
+    command -v "$cmd" >/dev/null || { echo "$cmd is required but not installed" >&2; exit 1; }
+done
 
 if [[ $# -eq 1 ]]; then
     selected=$1
